### ISSUE TITLE
请问modulemap文件怎么创建？ 在你的spec文件中没看见相关设置。

### ISSUE THREAD

**Issue by kb100824** [isandboy/SYWechatOpenSDK#1]
请问modulemap文件怎么创建？ 在你的spec文件中没看见相关设置。

**Comment by isandboy** [comment]
不用单独创建，pod 引入后会自动生成
![image](https://user-images.githubusercontent.com/19432890/116673321-d5801000-a9d5-11eb-9a8e-9449f6d98a3d.png)

**Comment by isandboy** [comment]
> 请问modulemap文件怎么创建？ 在你的spec文件中没看见相关设置。

不用单独创建，pod 引入后会生成
![image](https://user-images.githubusercontent.com/19432890/116673414-f0eb1b00-a9d5-11eb-8098-42bf4e5635c5.png)

**Comment by KBvsMJ** [comment]
确定你的x.podspec配置文件不需要做任何特殊设置？

**Comment by KBvsMJ** [comment]
> 确定你的x.podspec配置文件不需要做任何特殊设置？

@isandboy

**Comment by KBvsMJ** [comment]
看见你的库文件里面有这两个oc类文件。是不行必须要创建类似于这样oc类文件，然后pod的时候会自动生成modulemap文件。
![image](https://user-images.githubusercontent.com/8489350/117434533-5eabbf80-af5f-11eb-8c00-532f9f2cd76c.png)

**Comment by kb100824** [comment]
> 看见你的库文件里面有这两个oc类文件。是不行必须要创建类似于这样oc类文件，然后pod的时候会自动生成modulemap文件。
> ![image](https://user-images.githubusercontent.com/8489350/117434533-5eabbf80-af5f-11eb-8c00-532f9f2cd76c.png)

@isandboy

**Comment by isandboy** [comment]
> > 看见你的库文件里面有这两个oc类文件。是不行必须要创建类似于这样oc类文件，然后pod的时候会自动生成modulemap文件。
> > ![image](https://user-images.githubusercontent.com/8489350/117434533-5eabbf80-af5f-11eb-8c00-532f9f2cd76c.png)
> 
> @isandboy

**Comment by isandboy** [comment]
> > 看见你的库文件里面有这两个oc类文件。是不行必须要创建类似于这样oc类文件，然后pod的时候会自动生成modulemap文件。
> > ![image](https://user-images.githubusercontent.com/8489350/117434533-5eabbf80-af5f-11eb-8c00-532f9f2cd76c.png)
> 
> @isandboy

不是，modulemap和这文件没关系，modulemap文件是pod帮你自动生成的，这样就可以通过import 这种方式引入这个库了。

之所以创建这俩文件，是为了可以把WeChatSDK，包装成动态库
